version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: image-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: angel
      POSTGRES_DB: image_api_db
    ports:
      - "5433:5432"  # Host port 5433 mapped to container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pg-network

volumes:
  postgres_data:  # Volume to persist database data

networks:
  pg-network:
    driver: bridge
