version: '3.9'
services:
  nestapp:
    container_name: image-auth
    image: phanteon_image_auth/nestapp:1.0.0
    build: .
    ports:
      - '3000:3000'
    environment:
      - DB_TYPE=${DB_TYPE}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_DB=${PG_DB}
      - PG_PORT=5432
      - PG_HOST=db 
      - NODE_ENV=${NODE_ENV}      # Specify the environment (e.g., production, development)
      - JWT_SECRET=${JWT_SECRET} # Secret for JWT
    depends_on:
      - db
  db:
    container_name: image-auth-db
    image: postgres:latest
    environment:
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: angel
      POSTGRES_DB: image_api_db
    ports:
      - '${PG_PORT}:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}
