name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main  # Change this if your default branch is different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build
      - name: Create .env file
        run: |
          echo "DB_TYPE=${{ secrets.DB_TYPE }}" >> .env
          echo "PG_USER=${{ secrets.PG_USER }}" >> .env
          echo "PG_PASSWORD=${{ secrets.PG_PASSWORD }}" >> .env
          echo "PG_DB=${{ secrets.PG_DB }}" >> .env
          echo "PG_PORT=5432" >> .env
          echo "PG_HOST=${{ secrets.PG_HOST }}" >> .env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> .env
          echo "PORT=${{ secrets.PORT }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env
          echo "PIXABAY_URL=${{ secrets.PIXABAY_URL }}" >> .env
          echo "PIXABAY_API_KEY=${{ secrets.PIXABAY_API_KEY }}" >> .env
          echo "UNSPLASH_URL=${{ secrets.UNSPLASH_URL }}" >> ,env
          echo "UNSPLASH_ACCESS_KEY=${{ secrets.UNSPLASH_ACCESS_KEY }}" >> .env
          echo "STORYBLOCK_BASE_URL=${{ secrets.STORYBLOCK_BASE_URL }}" >> .env
          echo "STORYBLOCK_SEARCH_URL=${{ secrets.STORYBLOCK_SEARCH_URL }}" >> .env
          echo "STORYBLOCK_API_KEY=${{ secrets.STORYBLOCK_API_KEY }}" >> .env

      - name: Build Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-auth-db -f ./dockerfile .

      - name: Authenticate with Google Cloud
        run: echo "${{ secrets.GCP_SA_KEY }}" | base64 --decode > ${HOME}/gcloud-key.json && gcloud auth activate-service-account --key-file=${HOME}/gcloud-key.json

      - name: Push Docker image to Google Container Registry
        run: |
          gcloud auth configure-docker
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-auth-db

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy image-auth-db \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/image-auth-db \
            --platform managed \
            --region ${{ secrets.GCP_REGION }} \
            --allow-unauthenticated \
            --project ${{ secrets.GCP_PROJECT_ID }}